modLoader="javafml"
loaderVersion="[47,)"
license="MIT"

[[mods]]
modId="presidentstaxcollection"
version="1.0"
displayName="President's Tax Collection"
authors="Yumanyer"
description='''
Mod que agrega un Tax Collector: Una satira a los presidentes en el cual este spawenea pidiendo la paga de impuestos y tomando una postura hostil si el jugador se niega  a pagar.
'''

[[dependencies.presidentstaxcollection]]
modId="forge"
mandatory=true
versionRange="[47,)"
ordering="NONE"
side="BOTH"

[[dependencies.presidentstaxcollection]]
modId="minecraft"
mandatory=true
versionRange="[1.20.1]"
ordering="NONE"
side="BOTH"