modLoader="javafml"
loaderVersion="[47,)"
license="MIT"

[[mods]]
modId="presidentstaxcollection"
version="1.0"
displayName="President's Tax Collection"
authors="Manuel Pisoni"
description='''
Mod que agrega un Tax Collector: un sistema económico hostil donde el jugador debe pagar impuestos o enfrentar consecuencias.
'''

[[dependencies.presidentstaxcollection]]
modId="forge"
mandatory=true
versionRange="[47,)"
ordering="NONE"
side="BOTH"

[[dependencies.presidentstaxcollection]]
modId="minecraft"
mandatory=true
versionRange="[1.20.1]"
ordering="NONE"
side="BOTH"